[build]
builder = "NIXPACKS"

[deploy]
# Use Gunicorn to run the FastAPI app
startCommand = "gunicorn server:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"